import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'highlight.js/styles/github.css';  // Choose your preferred theme
import  {Roboto,  Poppins} from  "next/font/google"
import SideBar from "@/components/SideBar";
import RightSideBar from "@/components/RightSideBar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const  trendingTags  =  [{id:1, name:"chikenthief",  count:"200k"},  {id:2, name:"mesinkunkur", count:"10k"},  
  {id:3,  name:"trump", count:"200k"}, {name:"elon", count:"300k"}, {name:"aiagents", count:"40k"}]
const  robooto =  Roboto({weight:"100",  subsets:["latin"], variable:"--font-roboto"});
const  popins  =  Poppins({weight:"100",  subsets:["latin-ext"],variable:"--font-poppins"})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robooto.variable} ${popins.variable} antialiased min-h-screen bg-background`}
      >
       <div className="flex flex-col lg:flex-row w-full min-h-screen">
        <SideBar />
        <main  className="flex-1 w-full  lg:pr-[320px] lg:pl-[240px]">
          {children}
        </main>
        <RightSideBar trendingTags = {trendingTags} />
       </div>
      </body>
    </html>
  );
}
